; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Fluent Math"
; overridable so CI can pass the version from FluentMath.csproj via /DMyAppVersion
; local manual compiles keep using this fallback untouched
#ifndef MyAppVersion
  #define MyAppVersion "2.0.0"
#endif
#define MyAppPublisher "Daniel Čech"
#define MyAppExeName "FluentMath.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{1F029C99-A212-4D50-B14C-BA0B0C9965FA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
VersionInfoCompany={#MyAppPublisher}
VersionInfoProductName={#MyAppName}
VersionInfoDescription={#MyAppName} Setup
VersionInfoVersion={#MyAppVersion}.0
DefaultDirName={autopf}\{#MyAppName}
; an update from the Simple Calculator days would otherwise stay in the old folder; [Code] removes that one
UsePreviousAppDir=no
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=.\Output
OutputBaseFilename=FluentMath_Installer
SetupIconFile=..\FluentMath\Assets\Icon\Icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[InstallDelete]
; the shortcuts the app had while it was named Simple Calculator
Type: files; Name: "{autoprograms}\Simple Calculator.lnk"
Type: files; Name: "{autodesktop}\Simple Calculator.lnk"

[Files]
; must stay in sync with PublishDir in FluentMath/Properties/PublishProfiles/win-x64.pubxml
Source: "..\FluentMath\bin\x64\Release\net8.0-windows10.0.19041.0\publish\win-x64\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\FluentMath\bin\x64\Release\net8.0-windows10.0.19041.0\publish\win-x64\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
// up to v2.1.0 the app was named Simple Calculator and installed into a folder of that name; an update now
// installs into the new folder, and the old one is removed once the new files are in place
const
  // the AppId above, as its uninstall entry spells it
  UninstallKey = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{1F029C99-A212-4D50-B14C-BA0B0C9965FA}_is1';
  LegacyFolderName = 'Simple Calculator';
  LegacyExeName = 'Calculator_WinUI.exe';

var
  LegacyAppDir: String;

function InitializeSetup(): Boolean;
begin
  // read before anything is installed; afterwards the entry already points at the new folder
  if not RegQueryStringValue(HKLM64, UninstallKey, 'Inno Setup: App Path', LegacyAppDir) then
    LegacyAppDir := '';
  Result := True;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep <> ssPostInstall then Exit;
  if LegacyAppDir = '' then Exit;
  if CompareText(RemoveBackslashUnlessRoot(LegacyAppDir), RemoveBackslashUnlessRoot(ExpandConstant('{app}'))) = 0 then Exit;

  // the path came from a directory page back then and could point anywhere, so only a folder that carries
  // the old name and still holds the old executable is ours to delete
  if CompareText(ExtractFileName(RemoveBackslashUnlessRoot(LegacyAppDir)), LegacyFolderName) <> 0 then Exit;
  if not FileExists(AddBackslash(LegacyAppDir) + LegacyExeName) then Exit;

  // a copy of the old app that is still running keeps some files locked; those stay behind, the rest goes
  DelTree(LegacyAppDir, True, True, True);
end;

